INSERT INTO `colaborador` (`pergunta`,`tipo`) VALUES
('Como você se sente em relação ao reconhecimento de funcionários que apresentam um bom desempenho?','Escalonada'),
('A empresa faz você sentir importância no que faz?','Dicotômica'),
('Como você se sente em relação à política de remuneração, benefícios e promoções da empresa?','Escalonada'),
('Como você se sente em relação à  sua preparação para realização do seu trabalho diário?','Escalonada'),
('Você tem conhecimento das expectativas da empresa em relação ao seu trabalho?','Dicotômica'),
('Como você se sente em relação ao seu relacionamento profissional com os seus superiores?','Escalonada'),
('Como você se sente em relação à transparência no que se refere à tomada de decisões de seus superiores?','Escalonada'),
('O seu líder se importa com você como pessoa?','Dicotômica'),
('Você se sente apoiado em fazer o seu melhor todos os dias?','Dicotômica'),
('Sinto que o volume de serviço é adequado a minha jornada de trabalho?','Dicotômica'),
('Considero meu salário adequado em relação ao salário de outros colaboradores da empresa?','Dicotômica'),
('Considero meu salário adequado em relação ao salário de outras pessoas que executam tarefas semelhantes em outras empresas?','Dicotômica'),
('O líder está sempre pronto a prestar o suporte necessário a equipe?','Dicotômica'),
('O líder incentiva e aceita ideias e sugestões dos colaboradores?','Dicotômica'),
('A empresa ouve seus colaboradores e dá retorno?','Dicotômica'),
('Conheço as competências necessárias para meu crescimento na empresa?','Dicotômica'),
('Quando se entra nesta empresa, fazem você se sentir bem vindo?','Dicotômica'),
('A empresa tem foco total na satisfação do cliente?','Dicotômica'),
('Recomendo a empresa para amigos e parentes como um ótimo lugar para trabalhar?','Dicotômica'),
('Eu trocaria de emprego para ganhar 10% a mais no salário?','Dicotômica'),
('As pessoas aqui são bem tratadas independe de cor ou raça?','Dicotômica'),
('As pessoas aqui são bem tratadas independente da sua orientação política e religiosa?','Dicotômica'),
('Qual o seu nível de satisfação com o seu salário na empresa?','Escalonada'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por salário?','Dicotômica'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por problema pessoal?','Dicotômica'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por melhor oportunidade de emprego?','Dicotômica'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por benefícios?','Dicotômica'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por relacionamento com a liderança?','Dicotômica'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por relacionamento com os colegas?','Dicotômica'),
('Em sua opinião por que as pessoas deixam de trabalhar na empresa? Seria por condições de trabalho?','Dicotômica'),
('Qual é seu nível de satisfação em trabalhar nesta empresa?','Escalonada'),
('Qual seu nível de satisfação com a infraestrutura para comodidade e conforto (refeitório, descanso, higiene)?','Escalonada'),
('Qual seu nível de satisfação com a comunicação com sua equipe de trabalho?','Escalonada'),
('Qual seu nível de satisfação com a comunicação com outros departamentos?','Escalonada'),
('É tratado de forma respeitosa pelos colegas de trabalho?','Dicotômica'),
('É comunicado em tempo adequado sobre as mudanças na empresa?','Dicotômica'),
('Qual seu nível de satisfação com a se sentir estimulado para o trabalho em equipe?','Escalonada'),
('Seu potencial de trabalho está sendo aproveitado de forma adequada na sua área?','Dicotômica'),
('Suas sugestões são avaliadas pelo seu gestor?','Dicotômica'),
('Qual seu nível de satisfação com as oportunidades de crescimento profissional na empresa?','Escalonada'),
('Recebe elogios sinceros pelo seu trabalho?','Dicotômica'),
('Você tem oportunidade de aprendizado e desenvolvimento profissional na empresa?','Dicotômica'),
('Qual seu nível de satisfação com a realização profissional com o cargo?','Escalonada'),
('A comunicação do gestor é feita de forma transparente?','Dicotômica'),
('Seu gestor possui as competências necessárias para a função?','Dicotômica'),
('Confia que as decisões tomadas pelo gestor são adequadas para alcançar o resultado proposto?','Dicotômica'),
('Seu gestor compartilha a tomada de decisão com você?','Dicotômica'),
('A delegação das tarefas é feita de forma adequada para as suas habilidades?','Dicotômica'),
('Seu desempenho profissional é avaliado de forma adequada?','Dicotômica'),
('Sente seguro em relação à estabilidade no emprego?','Dicotômica'),
('Sua remuneração atende suas necessidades pessoais?','Dicotômica'),
('Os líderes sabem delegar tarefas?','Dicotômica'),
('Há unidade da equipe em torno dos objetivos?','Dicotômica'),
('Eu sou informado por meu líder sobre o que ele acha do meu desempenho.','Dicotômica'),
('Tenho confiança nas decisões do meu líder.','Dicotômica'),
('Meu trabalho está sendo bem aproveitado em minha área.','Dicotômica'),
('Periodicamente são feitas reuniões produtivas de nosso grupo de trabalho.','Dicotômica'),
('Sou elogiado por meu líder por meu trabalho.','Dicotômica'),
('O trabalho em equipe é incentivado por meu líder.','Dicotômica'),
('Acredito que meu líder é capaz para liderar.','Dicotômica'),
('Qual seu nível de satisfação com as oportunidades de crescimento profissional nesta empresa.','Escalonada'),
('Meu líder é um exemplo para o grupo.','Dicotômica'),
('Acredito que vou continuar nesta área por alguns anos.','Dicotômica');
